---
- name: deploy application
  hosts: app
  become: true
  tasks:

  - name: Install # по кааким-то причинам не устанавливается в подготовке образа (так что костыль
    apt:
      name: git
      state: present

  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/ubuntu/reddit
      version: monolith
    notify: reload puma

  - name: Bundle install
    bundler:
      state: present
      chdir: /home/ubuntu/reddit # <-- В какой директории выполнить команду bundle

  handlers:
  - name: reload puma
    systemd: name=puma state=restarted
